import pizza from '../assets/pizza.jpeg';
import salad from '../assets/salad.jpeg';
import cake from '../assets/cake.jpeg';
import fruitSalad from '../assets/fruit-salad.jpeg';

export const CollectionList = [
  {
    name: 'Pizza',
    category: 'Lunch',
    image: pizza,
    timeToPrepare: 20,
    servesHowMany: 3,
    directions: [
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Possimus accusamus sint eveniet reiciendis at soluta accusantium veritatis assumenda laborum voluptatem aliquid enim delectus, ratione suscipit laboriosam obcaecati sapiente velit unde?',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, quod?',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam perspiciatis velit sed veritatis a et aspernatur eaque mollitia ullam at!',
      'Lorem ipsum dolor sit.',
      'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Doloremque dicta excepturi reprehenderit mollitia maxime vel.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem et earum sit, beatae vitae laudantium dignissimos accusamus doloribus velit obcaecati totam ut iusto commodi quod recusandae, fugiat magni tempore modi.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel nobis eius tempora fugiat iure rerum non a molestiae, corrupti aperiam eveniet voluptate aliquid ullam quam, ea explicabo. Mollitia, beatae dolor.',
    ],
    ingredients: [
      'Lorem, ipsum.',
      'Lorem ipsum dolor sit amet.',
      'Lorem, ipsum dolor.',
      'Lorem ipsum dolor sit amet consectetur adipisicing.',
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corrupti, sunt?',
      'Lorem, ipsum dolor.',
      'more cheese please and thank you',
    ],
  },
  {
    name: 'Another Cool Dish',
    category: 'Lunch',
    image: salad,
    timeToPrepare: 20,
    servesHowMany: 2,
    directions: [
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Possimus accusamus sint eveniet reiciendis at soluta accusantium veritatis assumenda laborum voluptatem aliquid enim delectus, ratione suscipit laboriosam obcaecati sapiente velit unde?',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, quod?',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam perspiciatis velit sed veritatis a et aspernatur eaque mollitia ullam at!',
      'Lorem ipsum dolor sit.',
      'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Doloremque dicta excepturi reprehenderit mollitia maxime vel.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem et earum sit, beatae vitae laudantium dignissimos accusamus doloribus velit obcaecati totam ut iusto commodi quod recusandae, fugiat magni tempore modi.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel nobis eius tempora fugiat iure rerum non a molestiae, corrupti aperiam eveniet voluptate aliquid ullam quam, ea explicabo. Mollitia, beatae dolor.',
    ],
    ingredients: [
      'Lorem, ipsum.',
      'Lorem ipsum dolor sit amet.',
      'Lorem, ipsum dolor.',
      'Lorem ipsum dolor sit amet consectetur adipisicing.',
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corrupti, sunt?',
      'Lorem, ipsum dolor.',
      'more cheese please and thank you',
    ],
  },
  {
    name: 'Cool Name',
    category: 'Dessert',
    image: cake,
    timeToPrepare: 20,
    servesHowMany: 8,
    directions: [
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Possimus accusamus sint eveniet reiciendis at soluta accusantium veritatis assumenda laborum voluptatem aliquid enim delectus, ratione suscipit laboriosam obcaecati sapiente velit unde?',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, quod?',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam perspiciatis velit sed veritatis a et aspernatur eaque mollitia ullam at!',
      'Lorem ipsum dolor sit.',
      'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Doloremque dicta excepturi reprehenderit mollitia maxime vel.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem et earum sit, beatae vitae laudantium dignissimos accusamus doloribus velit obcaecati totam ut iusto commodi quod recusandae, fugiat magni tempore modi.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel nobis eius tempora fugiat iure rerum non a molestiae, corrupti aperiam eveniet voluptate aliquid ullam quam, ea explicabo. Mollitia, beatae dolor.',
    ],
    ingredients: [
      'Lorem, ipsum.',
      'Lorem ipsum dolor sit amet.',
      'Lorem, ipsum dolor.',
      'Lorem ipsum dolor sit amet consectetur adipisicing.',
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corrupti, sunt?',
      'Lorem, ipsum dolor.',
      'more cheese please and thank you',
    ],
  },
  {
    name: 'Another Cool Dish',
    category: 'Breakfast',
    image: fruitSalad,
    timeToPrepare: 10,
    servesHowMany: 3,
    directions: [
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Possimus accusamus sint eveniet reiciendis at soluta accusantium veritatis assumenda laborum voluptatem aliquid enim delectus, ratione suscipit laboriosam obcaecati sapiente velit unde?',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, quod?',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam perspiciatis velit sed veritatis a et aspernatur eaque mollitia ullam at!',
      'Lorem ipsum dolor sit.',
      'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Doloremque dicta excepturi reprehenderit mollitia maxime vel.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem et earum sit, beatae vitae laudantium dignissimos accusamus doloribus velit obcaecati totam ut iusto commodi quod recusandae, fugiat magni tempore modi.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel nobis eius tempora fugiat iure rerum non a molestiae, corrupti aperiam eveniet voluptate aliquid ullam quam, ea explicabo. Mollitia, beatae dolor.',
    ],
    ingredients: [
      'Lorem, ipsum.',
      'Lorem ipsum dolor sit amet.',
      'Lorem, ipsum dolor.',
      'Lorem ipsum dolor sit amet consectetur adipisicing.',
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corrupti, sunt?',
      'Lorem, ipsum dolor.',
      'more cheese please and thank you',
    ],
  },
];
