import pizza from '../assets/pizza.jpeg';
import salad from '../assets/salad.jpeg';
import cake from '../assets/cake.jpeg';
import fruitSalad from '../assets/fruit-salad.jpeg';

export const CollectionList = [
  {
    name: 'Cool Name',
    category: 'Late night snack',
    image: pizza,
    timeToPrepare: 20,
    directions: [
      'Directions 1 Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quis, rerum.',
      'Direction 2 Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus temporibus deserunt laboriosam culpa ex non exercitationem nisi quos, consequuntur maiores.',
      'Direction 3 Lorem ipsum dolor sit amet.',
      'Direction 4 Stir a little bit.',
      'Direction 5 Keep stirring.',
      'Direction 6 More lorem ipsum there you go Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eius quaerat molestiae aspernatur modi sed quasi. Quae facilis quos excepturi dicta harum, sed possimus autem architecto adipisci temporibus! Quod, tempora aut.',
    ],
    ingredients: ['salt', 'pepper', 'honey', 'smile', 'cheese', 'more cheese please and thank you'],
  },
  {
    name: 'Another Cool Dish',
    category: 'Lunch',
    image: salad,
    timeToPrepare: 20,

    directions: [
      'Directions 1 Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quis, rerum.',
      'Direction 2 Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus temporibus deserunt laboriosam culpa ex non exercitationem nisi quos, consequuntur maiores.',
      'Direction 3 Lorem ipsum dolor sit amet.',
      'Direction 4 Stir a little bit.',
      'Direction 5 Keep stirring.',
      'Direction 6 More lorem ipsum there you go Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eius quaerat molestiae aspernatur modi sed quasi. Quae facilis quos excepturi dicta harum, sed possimus autem architecto adipisci temporibus! Quod, tempora aut.',
    ],
    ingredients: ['lots of love', 'lots of CFA sauce', 'honey', 'smile', 'cheese', 'sriracha yay!'],
  },
  {
    name: 'Cool Name',
    category: 'Dessert',
    image: cake,
    timeToPrepare: 20,
    directions: [
      'Directions 1 Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quis, rerum.',
      'Direction 2 Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus temporibus deserunt laboriosam culpa ex non exercitationem nisi quos, consequuntur maiores.',
      'Direction 3 Lorem ipsum dolor sit amet.',
      'Direction 4 Stir a little bit.',
      'Direction 5 Keep stirring.',
      'Direction 6 More lorem ipsum there you go Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eius quaerat molestiae aspernatur modi sed quasi. Quae facilis quos excepturi dicta harum, sed possimus autem architecto adipisci temporibus! Quod, tempora aut.',
    ],
    ingredients: ['salt', 'pepper', 'honey', 'smile', 'cheese', 'more cheese please and thank you'],
  },
  {
    name: 'Another Cool Dish',
    category: 'Breakfast',
    image: fruitSalad,
    timeToPrepare: 10,
    directions: [
      'Directions 1 Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quis, rerum.',
      'Direction 2 Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus temporibus deserunt laboriosam culpa ex non exercitationem nisi quos, consequuntur maiores.',
      'Direction 3 Lorem ipsum dolor sit amet.',
      'Direction 4 Stir a little bit.',
      'Direction 5 Keep stirring.',
      'Direction 6 More lorem ipsum there you go Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eius quaerat molestiae aspernatur modi sed quasi. Quae facilis quos excepturi dicta harum, sed possimus autem architecto adipisci temporibus! Quod, tempora aut.',
    ],
    ingredients: ['lots of love', 'lots of CFA sauce', 'honey', 'smile', 'cheese', 'sriracha yay!'],
  },
  {
    name: 'Cool Name',
    category: 'Late night snack',
    image: pizza,
    timeToPrepare: 20,
    directions: [
      'Directions 1 Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quis, rerum.',
      'Direction 2 Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus temporibus deserunt laboriosam culpa ex non exercitationem nisi quos, consequuntur maiores.',
      'Direction 3 Lorem ipsum dolor sit amet.',
      'Direction 4 Stir a little bit.',
      'Direction 5 Keep stirring.',
      'Direction 6 More lorem ipsum there you go Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eius quaerat molestiae aspernatur modi sed quasi. Quae facilis quos excepturi dicta harum, sed possimus autem architecto adipisci temporibus! Quod, tempora aut.',
    ],
    ingredients: ['salt', 'pepper', 'honey', 'smile', 'cheese', 'more cheese please and thank you'],
  },
  {
    name: 'Another Cool Dish',
    category: 'Lunch',
    image: salad,
    timeToPrepare: 20,

    directions: [
      'Directions 1 Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quis, rerum.',
      'Direction 2 Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus temporibus deserunt laboriosam culpa ex non exercitationem nisi quos, consequuntur maiores.',
      'Direction 3 Lorem ipsum dolor sit amet.',
      'Direction 4 Stir a little bit.',
      'Direction 5 Keep stirring.',
      'Direction 6 More lorem ipsum there you go Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eius quaerat molestiae aspernatur modi sed quasi. Quae facilis quos excepturi dicta harum, sed possimus autem architecto adipisci temporibus! Quod, tempora aut.',
    ],
    ingredients: ['lots of love', 'lots of CFA sauce', 'honey', 'smile', 'cheese', 'sriracha yay!'],
  },
  {
    name: 'Cool Name',
    category: 'Dessert',
    image: cake,
    timeToPrepare: 20,
    directions: [
      'Directions 1 Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quis, rerum.',
      'Direction 2 Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus temporibus deserunt laboriosam culpa ex non exercitationem nisi quos, consequuntur maiores.',
      'Direction 3 Lorem ipsum dolor sit amet.',
      'Direction 4 Stir a little bit.',
      'Direction 5 Keep stirring.',
      'Direction 6 More lorem ipsum there you go Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eius quaerat molestiae aspernatur modi sed quasi. Quae facilis quos excepturi dicta harum, sed possimus autem architecto adipisci temporibus! Quod, tempora aut.',
    ],
    ingredients: ['salt', 'pepper', 'honey', 'smile', 'cheese', 'more cheese please and thank you'],
  },
  {
    name: 'Another Cool Dish',
    category: 'Breakfast',
    image: fruitSalad,
    timeToPrepare: 10,
    directions: [
      'Directions 1 Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quis, rerum.',
      'Direction 2 Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus temporibus deserunt laboriosam culpa ex non exercitationem nisi quos, consequuntur maiores.',
      'Direction 3 Lorem ipsum dolor sit amet.',
      'Direction 4 Stir a little bit.',
      'Direction 5 Keep stirring.',
      'Direction 6 More lorem ipsum there you go Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eius quaerat molestiae aspernatur modi sed quasi. Quae facilis quos excepturi dicta harum, sed possimus autem architecto adipisci temporibus! Quod, tempora aut.',
    ],
    ingredients: ['lots of love', 'lots of CFA sauce', 'honey', 'smile', 'cheese', 'sriracha yay!'],
  },
  {
    name: 'Cool Name',
    category: 'Late night snack',
    image: pizza,
    timeToPrepare: 20,
    directions: [
      'Directions 1 Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quis, rerum.',
      'Direction 2 Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus temporibus deserunt laboriosam culpa ex non exercitationem nisi quos, consequuntur maiores.',
      'Direction 3 Lorem ipsum dolor sit amet.',
      'Direction 4 Stir a little bit.',
      'Direction 5 Keep stirring.',
      'Direction 6 More lorem ipsum there you go Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eius quaerat molestiae aspernatur modi sed quasi. Quae facilis quos excepturi dicta harum, sed possimus autem architecto adipisci temporibus! Quod, tempora aut.',
    ],
    ingredients: ['salt', 'pepper', 'honey', 'smile', 'cheese', 'more cheese please and thank you'],
  },
  {
    name: 'Another Cool Dish',
    category: 'Lunch',
    image: salad,
    timeToPrepare: 20,

    directions: [
      'Directions 1 Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quis, rerum.',
      'Direction 2 Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus temporibus deserunt laboriosam culpa ex non exercitationem nisi quos, consequuntur maiores.',
      'Direction 3 Lorem ipsum dolor sit amet.',
      'Direction 4 Stir a little bit.',
      'Direction 5 Keep stirring.',
      'Direction 6 More lorem ipsum there you go Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eius quaerat molestiae aspernatur modi sed quasi. Quae facilis quos excepturi dicta harum, sed possimus autem architecto adipisci temporibus! Quod, tempora aut.',
    ],
    ingredients: ['lots of love', 'lots of CFA sauce', 'honey', 'smile', 'cheese', 'sriracha yay!'],
  },
  {
    name: 'Cool Name',
    category: 'Dessert',
    image: cake,
    timeToPrepare: 20,
    directions: [
      'Directions 1 Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quis, rerum.',
      'Direction 2 Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus temporibus deserunt laboriosam culpa ex non exercitationem nisi quos, consequuntur maiores.',
      'Direction 3 Lorem ipsum dolor sit amet.',
      'Direction 4 Stir a little bit.',
      'Direction 5 Keep stirring.',
      'Direction 6 More lorem ipsum there you go Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eius quaerat molestiae aspernatur modi sed quasi. Quae facilis quos excepturi dicta harum, sed possimus autem architecto adipisci temporibus! Quod, tempora aut.',
    ],
    ingredients: ['salt', 'pepper', 'honey', 'smile', 'cheese', 'more cheese please and thank you'],
  },
  {
    name: 'Another Cool Dish',
    category: 'Breakfast',
    image: fruitSalad,
    timeToPrepare: 10,
    directions: [
      'Directions 1 Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quis, rerum.',
      'Direction 2 Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus temporibus deserunt laboriosam culpa ex non exercitationem nisi quos, consequuntur maiores.',
      'Direction 3 Lorem ipsum dolor sit amet.',
      'Direction 4 Stir a little bit.',
      'Direction 5 Keep stirring.',
      'Direction 6 More lorem ipsum there you go Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eius quaerat molestiae aspernatur modi sed quasi. Quae facilis quos excepturi dicta harum, sed possimus autem architecto adipisci temporibus! Quod, tempora aut.',
    ],
    ingredients: ['lots of love', 'lots of CFA sauce', 'honey', 'smile', 'cheese', 'sriracha yay!'],
  },
  {
    name: 'Cool Name',
    category: 'Late night snack',
    image: pizza,
    timeToPrepare: 20,
    directions: [
      'Directions 1 Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quis, rerum.',
      'Direction 2 Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus temporibus deserunt laboriosam culpa ex non exercitationem nisi quos, consequuntur maiores.',
      'Direction 3 Lorem ipsum dolor sit amet.',
      'Direction 4 Stir a little bit.',
      'Direction 5 Keep stirring.',
      'Direction 6 More lorem ipsum there you go Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eius quaerat molestiae aspernatur modi sed quasi. Quae facilis quos excepturi dicta harum, sed possimus autem architecto adipisci temporibus! Quod, tempora aut.',
    ],
    ingredients: ['salt', 'pepper', 'honey', 'smile', 'cheese', 'more cheese please and thank you'],
  },
  {
    name: 'Another Cool Dish',
    category: 'Lunch',
    image: salad,
    timeToPrepare: 20,

    directions: [
      'Directions 1 Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quis, rerum.',
      'Direction 2 Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus temporibus deserunt laboriosam culpa ex non exercitationem nisi quos, consequuntur maiores.',
      'Direction 3 Lorem ipsum dolor sit amet.',
      'Direction 4 Stir a little bit.',
      'Direction 5 Keep stirring.',
      'Direction 6 More lorem ipsum there you go Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eius quaerat molestiae aspernatur modi sed quasi. Quae facilis quos excepturi dicta harum, sed possimus autem architecto adipisci temporibus! Quod, tempora aut.',
    ],
    ingredients: ['lots of love', 'lots of CFA sauce', 'honey', 'smile', 'cheese', 'sriracha yay!'],
  },
  {
    name: 'Cool Name',
    category: 'Dessert',
    image: cake,
    timeToPrepare: 20,
    directions: [
      'Directions 1 Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quis, rerum.',
      'Direction 2 Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus temporibus deserunt laboriosam culpa ex non exercitationem nisi quos, consequuntur maiores.',
      'Direction 3 Lorem ipsum dolor sit amet.',
      'Direction 4 Stir a little bit.',
      'Direction 5 Keep stirring.',
      'Direction 6 More lorem ipsum there you go Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eius quaerat molestiae aspernatur modi sed quasi. Quae facilis quos excepturi dicta harum, sed possimus autem architecto adipisci temporibus! Quod, tempora aut.',
    ],
    ingredients: ['salt', 'pepper', 'honey', 'smile', 'cheese', 'more cheese please and thank you'],
  },
  {
    name: 'Another Cool Dish',
    category: 'Breakfast',
    image: fruitSalad,
    timeToPrepare: 10,
    directions: [
      'Directions 1 Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quis, rerum.',
      'Direction 2 Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus temporibus deserunt laboriosam culpa ex non exercitationem nisi quos, consequuntur maiores.',
      'Direction 3 Lorem ipsum dolor sit amet.',
      'Direction 4 Stir a little bit.',
      'Direction 5 Keep stirring.',
      'Direction 6 More lorem ipsum there you go Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eius quaerat molestiae aspernatur modi sed quasi. Quae facilis quos excepturi dicta harum, sed possimus autem architecto adipisci temporibus! Quod, tempora aut.',
    ],
    ingredients: ['lots of love', 'lots of CFA sauce', 'honey', 'smile', 'cheese', 'sriracha yay!'],
  },
  {
    name: 'Cool Name',
    category: 'Late night snack',
    image: pizza,
    timeToPrepare: 20,
    directions: [
      'Directions 1 Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quis, rerum.',
      'Direction 2 Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus temporibus deserunt laboriosam culpa ex non exercitationem nisi quos, consequuntur maiores.',
      'Direction 3 Lorem ipsum dolor sit amet.',
      'Direction 4 Stir a little bit.',
      'Direction 5 Keep stirring.',
      'Direction 6 More lorem ipsum there you go Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eius quaerat molestiae aspernatur modi sed quasi. Quae facilis quos excepturi dicta harum, sed possimus autem architecto adipisci temporibus! Quod, tempora aut.',
    ],
    ingredients: ['salt', 'pepper', 'honey', 'smile', 'cheese', 'more cheese please and thank you'],
  },
  {
    name: 'Another Cool Dish',
    category: 'Lunch',
    image: salad,
    timeToPrepare: 20,

    directions: [
      'Directions 1 Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quis, rerum.',
      'Direction 2 Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus temporibus deserunt laboriosam culpa ex non exercitationem nisi quos, consequuntur maiores.',
      'Direction 3 Lorem ipsum dolor sit amet.',
      'Direction 4 Stir a little bit.',
      'Direction 5 Keep stirring.',
      'Direction 6 More lorem ipsum there you go Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eius quaerat molestiae aspernatur modi sed quasi. Quae facilis quos excepturi dicta harum, sed possimus autem architecto adipisci temporibus! Quod, tempora aut.',
    ],
    ingredients: ['lots of love', 'lots of CFA sauce', 'honey', 'smile', 'cheese', 'sriracha yay!'],
  },
  {
    name: 'Cool Name',
    category: 'Dessert',
    image: cake,
    timeToPrepare: 20,
    directions: [
      'Directions 1 Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quis, rerum.',
      'Direction 2 Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus temporibus deserunt laboriosam culpa ex non exercitationem nisi quos, consequuntur maiores.',
      'Direction 3 Lorem ipsum dolor sit amet.',
      'Direction 4 Stir a little bit.',
      'Direction 5 Keep stirring.',
      'Direction 6 More lorem ipsum there you go Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eius quaerat molestiae aspernatur modi sed quasi. Quae facilis quos excepturi dicta harum, sed possimus autem architecto adipisci temporibus! Quod, tempora aut.',
    ],
    ingredients: ['salt', 'pepper', 'honey', 'smile', 'cheese', 'more cheese please and thank you'],
  },
  {
    name: 'Another Cool Dish',
    category: 'Breakfast',
    image: fruitSalad,
    timeToPrepare: 10,
    directions: [
      'Directions 1 Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quis, rerum.',
      'Direction 2 Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus temporibus deserunt laboriosam culpa ex non exercitationem nisi quos, consequuntur maiores.',
      'Direction 3 Lorem ipsum dolor sit amet.',
      'Direction 4 Stir a little bit.',
      'Direction 5 Keep stirring.',
      'Direction 6 More lorem ipsum there you go Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eius quaerat molestiae aspernatur modi sed quasi. Quae facilis quos excepturi dicta harum, sed possimus autem architecto adipisci temporibus! Quod, tempora aut.',
    ],
    ingredients: ['lots of love', 'lots of CFA sauce', 'honey', 'smile', 'cheese', 'sriracha yay!'],
  },
  {
    name: 'Cool Name',
    category: 'Late night snack',
    image: pizza,
    timeToPrepare: 20,
    directions: [
      'Directions 1 Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quis, rerum.',
      'Direction 2 Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus temporibus deserunt laboriosam culpa ex non exercitationem nisi quos, consequuntur maiores.',
      'Direction 3 Lorem ipsum dolor sit amet.',
      'Direction 4 Stir a little bit.',
      'Direction 5 Keep stirring.',
      'Direction 6 More lorem ipsum there you go Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eius quaerat molestiae aspernatur modi sed quasi. Quae facilis quos excepturi dicta harum, sed possimus autem architecto adipisci temporibus! Quod, tempora aut.',
    ],
    ingredients: ['salt', 'pepper', 'honey', 'smile', 'cheese', 'more cheese please and thank you'],
  },
  {
    name: 'Another Cool Dish',
    category: 'Lunch',
    image: salad,
    timeToPrepare: 20,

    directions: [
      'Directions 1 Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quis, rerum.',
      'Direction 2 Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus temporibus deserunt laboriosam culpa ex non exercitationem nisi quos, consequuntur maiores.',
      'Direction 3 Lorem ipsum dolor sit amet.',
      'Direction 4 Stir a little bit.',
      'Direction 5 Keep stirring.',
      'Direction 6 More lorem ipsum there you go Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eius quaerat molestiae aspernatur modi sed quasi. Quae facilis quos excepturi dicta harum, sed possimus autem architecto adipisci temporibus! Quod, tempora aut.',
    ],
    ingredients: ['lots of love', 'lots of CFA sauce', 'honey', 'smile', 'cheese', 'sriracha yay!'],
  },
  {
    name: 'Cool Name',
    category: 'Dessert',
    image: cake,
    timeToPrepare: 20,
    directions: [
      'Directions 1 Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quis, rerum.',
      'Direction 2 Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus temporibus deserunt laboriosam culpa ex non exercitationem nisi quos, consequuntur maiores.',
      'Direction 3 Lorem ipsum dolor sit amet.',
      'Direction 4 Stir a little bit.',
      'Direction 5 Keep stirring.',
      'Direction 6 More lorem ipsum there you go Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eius quaerat molestiae aspernatur modi sed quasi. Quae facilis quos excepturi dicta harum, sed possimus autem architecto adipisci temporibus! Quod, tempora aut.',
    ],
    ingredients: ['salt', 'pepper', 'honey', 'smile', 'cheese', 'more cheese please and thank you'],
  },
  {
    name: 'Another Cool Dish',
    category: 'Breakfast',
    image: fruitSalad,
    timeToPrepare: 10,
    directions: [
      'Directions 1 Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quis, rerum.',
      'Direction 2 Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus temporibus deserunt laboriosam culpa ex non exercitationem nisi quos, consequuntur maiores.',
      'Direction 3 Lorem ipsum dolor sit amet.',
      'Direction 4 Stir a little bit.',
      'Direction 5 Keep stirring.',
      'Direction 6 More lorem ipsum there you go Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eius quaerat molestiae aspernatur modi sed quasi. Quae facilis quos excepturi dicta harum, sed possimus autem architecto adipisci temporibus! Quod, tempora aut.',
    ],
    ingredients: ['lots of love', 'lots of CFA sauce', 'honey', 'smile', 'cheese', 'sriracha yay!'],
  },
  {
    name: 'Cool Name',
    category: 'Late night snack',
    image: pizza,
    timeToPrepare: 20,
    directions: [
      'Directions 1 Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quis, rerum.',
      'Direction 2 Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus temporibus deserunt laboriosam culpa ex non exercitationem nisi quos, consequuntur maiores.',
      'Direction 3 Lorem ipsum dolor sit amet.',
      'Direction 4 Stir a little bit.',
      'Direction 5 Keep stirring.',
      'Direction 6 More lorem ipsum there you go Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eius quaerat molestiae aspernatur modi sed quasi. Quae facilis quos excepturi dicta harum, sed possimus autem architecto adipisci temporibus! Quod, tempora aut.',
    ],
    ingredients: ['salt', 'pepper', 'honey', 'smile', 'cheese', 'more cheese please and thank you'],
  },
  {
    name: 'Another Cool Dish',
    category: 'Lunch',
    image: salad,
    timeToPrepare: 20,

    directions: [
      'Directions 1 Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quis, rerum.',
      'Direction 2 Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus temporibus deserunt laboriosam culpa ex non exercitationem nisi quos, consequuntur maiores.',
      'Direction 3 Lorem ipsum dolor sit amet.',
      'Direction 4 Stir a little bit.',
      'Direction 5 Keep stirring.',
      'Direction 6 More lorem ipsum there you go Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eius quaerat molestiae aspernatur modi sed quasi. Quae facilis quos excepturi dicta harum, sed possimus autem architecto adipisci temporibus! Quod, tempora aut.',
    ],
    ingredients: ['lots of love', 'lots of CFA sauce', 'honey', 'smile', 'cheese', 'sriracha yay!'],
  },
  {
    name: 'Cool Name',
    category: 'Dessert',
    image: cake,
    timeToPrepare: 20,
    directions: [
      'Directions 1 Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quis, rerum.',
      'Direction 2 Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus temporibus deserunt laboriosam culpa ex non exercitationem nisi quos, consequuntur maiores.',
      'Direction 3 Lorem ipsum dolor sit amet.',
      'Direction 4 Stir a little bit.',
      'Direction 5 Keep stirring.',
      'Direction 6 More lorem ipsum there you go Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eius quaerat molestiae aspernatur modi sed quasi. Quae facilis quos excepturi dicta harum, sed possimus autem architecto adipisci temporibus! Quod, tempora aut.',
    ],
    ingredients: ['salt', 'pepper', 'honey', 'smile', 'cheese', 'more cheese please and thank you'],
  },
  {
    name: 'Another Cool Dish',
    category: 'Breakfast',
    image: fruitSalad,
    timeToPrepare: 10,
    directions: [
      'Directions 1 Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quis, rerum.',
      'Direction 2 Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus temporibus deserunt laboriosam culpa ex non exercitationem nisi quos, consequuntur maiores.',
      'Direction 3 Lorem ipsum dolor sit amet.',
      'Direction 4 Stir a little bit.',
      'Direction 5 Keep stirring.',
      'Direction 6 More lorem ipsum there you go Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eius quaerat molestiae aspernatur modi sed quasi. Quae facilis quos excepturi dicta harum, sed possimus autem architecto adipisci temporibus! Quod, tempora aut.',
    ],
    ingredients: ['lots of love', 'lots of CFA sauce', 'honey', 'smile', 'cheese', 'sriracha yay!'],
  },
  {
    name: 'Cool Name',
    category: 'Late night snack',
    image: pizza,
    timeToPrepare: 20,
    directions: [
      'Directions 1 Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quis, rerum.',
      'Direction 2 Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus temporibus deserunt laboriosam culpa ex non exercitationem nisi quos, consequuntur maiores.',
      'Direction 3 Lorem ipsum dolor sit amet.',
      'Direction 4 Stir a little bit.',
      'Direction 5 Keep stirring.',
      'Direction 6 More lorem ipsum there you go Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eius quaerat molestiae aspernatur modi sed quasi. Quae facilis quos excepturi dicta harum, sed possimus autem architecto adipisci temporibus! Quod, tempora aut.',
    ],
    ingredients: ['salt', 'pepper', 'honey', 'smile', 'cheese', 'more cheese please and thank you'],
  },
  {
    name: 'Another Cool Dish',
    category: 'Lunch',
    image: salad,
    timeToPrepare: 20,

    directions: [
      'Directions 1 Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quis, rerum.',
      'Direction 2 Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus temporibus deserunt laboriosam culpa ex non exercitationem nisi quos, consequuntur maiores.',
      'Direction 3 Lorem ipsum dolor sit amet.',
      'Direction 4 Stir a little bit.',
      'Direction 5 Keep stirring.',
      'Direction 6 More lorem ipsum there you go Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eius quaerat molestiae aspernatur modi sed quasi. Quae facilis quos excepturi dicta harum, sed possimus autem architecto adipisci temporibus! Quod, tempora aut.',
    ],
    ingredients: ['lots of love', 'lots of CFA sauce', 'honey', 'smile', 'cheese', 'sriracha yay!'],
  },
  {
    name: 'Cool Name',
    category: 'Dessert',
    image: cake,
    timeToPrepare: 20,
    directions: [
      'Directions 1 Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quis, rerum.',
      'Direction 2 Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus temporibus deserunt laboriosam culpa ex non exercitationem nisi quos, consequuntur maiores.',
      'Direction 3 Lorem ipsum dolor sit amet.',
      'Direction 4 Stir a little bit.',
      'Direction 5 Keep stirring.',
      'Direction 6 More lorem ipsum there you go Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eius quaerat molestiae aspernatur modi sed quasi. Quae facilis quos excepturi dicta harum, sed possimus autem architecto adipisci temporibus! Quod, tempora aut.',
    ],
    ingredients: ['salt', 'pepper', 'honey', 'smile', 'cheese', 'more cheese please and thank you'],
  },
  {
    name: 'Another Cool Dish',
    category: 'Breakfast',
    image: fruitSalad,
    timeToPrepare: 10,
    directions: [
      'Directions 1 Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quis, rerum.',
      'Direction 2 Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus temporibus deserunt laboriosam culpa ex non exercitationem nisi quos, consequuntur maiores.',
      'Direction 3 Lorem ipsum dolor sit amet.',
      'Direction 4 Stir a little bit.',
      'Direction 5 Keep stirring.',
      'Direction 6 More lorem ipsum there you go Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eius quaerat molestiae aspernatur modi sed quasi. Quae facilis quos excepturi dicta harum, sed possimus autem architecto adipisci temporibus! Quod, tempora aut.',
    ],
    ingredients: ['lots of love', 'lots of CFA sauce', 'honey', 'smile', 'cheese', 'sriracha yay!'],
  },
];
